/*jshint esversion: 6 */

const path = require('path');
const LodashModuleReplacementPlugin = require('lodash-webpack-plugin');
const webpack = require('webpack');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const HtmlWebpackPlugin = require('html-webpack-plugin');

// workaround to remove empty js files generated by mini css
class MiniCssExtractPluginCleanup {
  constructor(deleteWhere = /sensu-app\.(dark|light)\.js(\.map)?$/) {
    this.shouldDelete = new RegExp(deleteWhere);
  }
  apply(compiler) {
    compiler.hooks.emit.tapAsync("MiniCssExtractPluginCleanup", (compilation, callback) => {
      Object.keys(compilation.assets).forEach((asset) => {
        if (this.shouldDelete.test(asset)) {
          delete compilation.assets[asset];
        }
      });
      callback();
    });
  }
}

module.exports = {
  performance: {
    hints: process.env.NODE_ENV === 'production' ? "warning" : false
  },
  devtool: "inline-source-map",
  mode: 'development',
  watch: true,
  watchOptions: {
    poll: 1000,
    ignored: ['src/**/*.js', 'node_modules']
  },
  node: {
    fs: 'empty'
  },
  target: 'node',
  context: path.join(__dirname, 'src'),
  entry: {
    'module': './module.ts',
    'event-drops': path.resolve(__dirname, 'src/sass/event-drops.scss')
  },
  output: {
    filename: '[name].js',
    path: path.join(__dirname, 'dist'),
    libraryTarget: 'amd'
  },
  externals: [
    'angular',
    'lodash',
    'app/core/utils/kbn',
    function (context, request, callback) {
      var prefix = 'grafana/';
      if (request.indexOf(prefix) === 0) {
        return callback(null, request.substr(prefix.length));
      }
      callback();
    }
  ],
  plugins: [
    new CleanWebpackPlugin('dist', { allowExternal: true }),
    new webpack.optimize.OccurrenceOrderPlugin(),
    new LodashModuleReplacementPlugin(),
    new MiniCssExtractPlugin({
      filename: 'css/[name].css',
    }),
    new MiniCssExtractPluginCleanup(),
    new CopyWebpackPlugin([
      { from: 'plugin.json', to: '.' },
      { from: '../README.md', to: '.' },
      { from: 'img/*', to: '.'},
      { from: '*.html', to: '.' }
    ])
  ],
  resolve: {
    modules: [path.resolve(__dirname, 'src'), 'node_modules'],
    extensions: ['.ts', '.tsx', '.js'],
  },
  module: {
    rules: [
      { test: /\.tsx?$/,
          loaders: [
            "ts-loader"
          ],
          exclude: [/(node_modules)/],
      },
      {
        test: /\.html$/,
        exclude: [/node_modules/],
        use: {
          loader: 'html-loader'
        },
      },
      {
        test: /\.s[c|a]ss$/,
        use: ['style-loader', MiniCssExtractPlugin.loader, 'css-loader', 'postcss-loader', 'sass-loader']
      }
    ]
  }
};